### ISSUE TITLE
[save_index] how can I save the index file (*.bin) to local FS

### ISSUE THREAD

**Issue by jlia0** [ShravanSunder/hnswlib-wasm#6]
Is there a way to save the index file from the virtual FS from Emscripten to local FS? Or export the `*.bin` data.

**Comment by jlia0** [comment]
@ShravanSunder Thanks!

**Comment by ShravanSunder** [comment]
@jlia0 currently the nodeFS system is disabled!  please use hnswlib-node library for node access.

**Comment by ShravanSunder** [comment]
here's an example:
<img width="745" alt="2023-04-25 0402 Code hnswlibService ts — 2023-03 ghostai-dev" src="https://user-images.githubusercontent.com/5294949/234433304-1a6a2f38-783b-4f2a-83e9-120bdc262b09.png">


<img width="1175" alt="2023-04-25 0401 Obsidian I am making copiesjjj - test-vault - Obsidian v1 2 2" src="https://user-images.githubusercontent.com/5294949/234433274-2767b841-900b-40e1-871d-fc9b19b12015.png">

**Comment by lhr0909** [comment]
Oh nice! @ShravanSunder you are using the lib in obsidian now? Do you have an example repo on how you do that? I have been wanting to set up a vector storage as an obsidian plugin but couldn't find a way to do so. How much can you store inside Obsidian app indexDB?

I am thinking to add a feature to support MemFS, then add a wrapper method to export the bin file as binary so the developers have the liberty to store anywhere they want.

**Comment by ShravanSunder** [comment]
@lhr0909 i actually moved on from that project, but i did have it working in the browser electron process and browser.   I don't have anything that I can show right now my repo has mutated and gone in a different direction. 
> NOTE: hnswlib-wasm only works in a browser environment

The reason is:  there's a lot of gotcha's in getting IDBFS/emscripten FS working with both node and browser.   See https://github.com/ShravanSunder/hnswlib-wasm/blob/6ea37649da9f637900cc522502297cd04076dd4d/src/wrapper.cpp#L35 you can check out the history
Here is their references:  https://emscripten.org/docs/api_reference/Filesystem-API.html

i had many trials to get it to work with both node/browser, but there's a lot of hard coded globals check in emscripten that causes incompatibilities.

If you have some other more reliable way of getting data out of wasm memory space/ wasm FS then that might work.  Currently IDBFS won't work in node.  You can use `hnswlib-node` and use `hnswlib-wasm` for browser, but i understand that's also redundant work.  


WasmFS might make things better but its not ready: https://emscripten.org/docs/api_reference/Filesystem-API.html#new-file-system-wasmfs
